'use strict';

// K.1 / A5 / K.3 - prospect research wiring inside ZTech.
//
// K.1  the prebuilt CommonJS bundle lives under src/ so electron-builder ships it,
//      and the three runtime dependencies are real `dependencies`.
// A5   the database is open before the research service is constructed, window
//      creation is never blocked on the network, and quit closes the transport.
// K.3   A6 stays deferred: ZTech has no Lead Agent, so evidenceForLeadAgent() is
//      unreachable.

const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = path.join(__dirname, '..');
const pkg = require(path.join(root, 'package.json'));
const mainSource = fs.readFileSync(path.join(root, 'main.js'), 'utf8');
const preloadSource = fs.readFileSync(path.join(root, 'preload.js'), 'utf8');
const rendererSource = fs.readFileSync(path.join(root, 'src', 'renderer', 'renderer.js'), 'utf8');
const htmlSource = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const researchDir = path.join(root, 'src', 'main', 'prospect-research');
const bundlePath = path.join(researchDir, 'prospect-research.cjs');
const bundleSource = fs.readFileSync(bundlePath, 'utf8');
const serviceSource = fs.readFileSync(path.join(researchDir, 'research-service.js'), 'utf8');
const storeSource = fs.readFileSync(path.join(researchDir, 'sql-research-store.js'), 'utf8');
const senderSource = fs.readFileSync(path.join(researchDir, 'trusted-sender.js'), 'utf8');
const ipcSource = fs.readFileSync(path.join(researchDir, 'research-ipc.js'), 'utf8');
const quarantineSource = fs.readFileSync(path.join(researchDir, 'quarantine-sink.js'), 'utf8');
const credentialSource = fs.readFileSync(path.join(researchDir, 'credential-source.js'), 'utf8');

let passed = 0;
let failed = 0;
const tests = [];
function test(name, fn) {
  tests.push([name, fn]);
}

const MODULE_VERSION = '0.1.2';

function region(source, startMarker, endMarker) {
  const s = source.indexOf(startMarker);
  assert.ok(s > -1, 'start marker present: ' + startMarker);
  const e = source.indexOf(endMarker, s + startMarker.length);
  assert.ok(e > s, 'end marker after start: ' + endMarker);
  return source.slice(s, e);
}

/** The channel names research-ipc.js actually registers. */
function researchChannels() {
  return [...ipcSource.matchAll(/ipcMain\.handle\(CHANNELS\.(\w+)/g)]
    .map(m => `prospect-research:${m[1].replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())}`);
}

// --- K.1 -------------------------------------------------------------------

test('1. the prebuilt bundle sits under src/ so build.files already ships it', () => {
  assert.ok(fs.existsSync(bundlePath), 'bundle present at src/main/prospect-research/prospect-research.cjs');
  assert.ok(pkg.build.files.includes('src/**/*'), 'build.files still ships all of src/');
  const rel = path.relative(root, bundlePath).replace(/\\/g, '/');
  assert.ok(rel.startsWith('src/'), 'bundle is inside the packaged file list');
  assert.deepStrictEqual(pkg.build.asarUnpack, ['node_modules/sql.js/dist/sql-wasm.wasm'],
    'asarUnpack unchanged: only sql.js needs unpacking');
});

test('2. the bundle is pinned to module version 0.1.2', () => {
  assert.strictEqual(bundleSource.split('\n')[0].trim(),
    `/* ztech-prospect-research ${MODULE_VERSION} - generated by npm run build:cjs, do not edit */`,
    'bundle header carries the pinned version');
  assert.ok(!bundleSource.includes('0.1.1'), 'no older version referenced');
});

test('3. the bundle exposes exactly the surface ZTech uses', () => {
  const bundle = require(bundlePath);
  assert.deepStrictEqual(Object.keys(bundle).sort(),
    ['FakeResearchProvider', 'InMemoryQuarantine', 'InMemoryResearchStateStore', 'StaleRecordError', 'createProspectResearch'],
    'public surface unchanged');
  assert.strictEqual(typeof bundle.createProspectResearch, 'function', 'composition entry point available');
  assert.strictEqual(typeof bundle.StaleRecordError, 'function', 'stale error class available for A1');
  const err = new bundle.StaleRecordError('rec-9');
  assert.strictEqual(err.name, 'StaleRecordError', 'error name preserved');
  assert.ok(err instanceof Error, 'error extends Error');
});

test('4. the bundle needs only the three declared runtime dependencies', () => {
  const required = [...bundleSource.matchAll(/require\("([^"]+)"\)/g)].map((m) => m[1]);
  const external = [...new Set(required)].filter((r) => !r.startsWith('node:')).sort();
  assert.deepStrictEqual(external, ['@modelcontextprotocol/client', 'ajv-formats', 'ajv/dist/2020'],
    'no unexpected external requires');
  const builtins = [...new Set(required)].filter((r) => r.startsWith('node:')).sort();
  assert.deepStrictEqual(builtins, ['node:crypto', 'node:fs/promises'], 'only Node built-ins besides the deps');
  assert.ok(!bundleSource.includes('import('), 'no dynamic ESM import, so plain require() is enough');
});

test('5. the three dependencies are in dependencies, not devDependencies', () => {
  for (const [name, range] of [
    ['@modelcontextprotocol/client', '^2.1.0'],
    ['ajv', '^8.20.0'],
    ['ajv-formats', '^3.0.1']
  ]) {
    assert.strictEqual(pkg.dependencies[name], range, name + ' pinned in dependencies');
    assert.strictEqual(pkg.devDependencies[name], undefined, name + ' absent from devDependencies');
  }
});

test('6. the bundle resolves ajv 8 and ajv/dist/2020 from its own directory', () => {
  const from = path.join(researchDir, 'probe.js');
  const ajvPath = require.resolve('ajv/package.json', { paths: [researchDir] });
  const ajvVersion = require(ajvPath).version;
  assert.ok(ajvVersion.startsWith('8.'), 'ajv 8 is what the bundle will load, got ' + ajvVersion);
  const resolved = require.resolve('ajv/dist/2020', { paths: [researchDir] });
  assert.ok(resolved.includes('ajv'), 'ajv/dist/2020 resolves');
  void from;
  // And the real thing: the module's contract validator must construct.
  const Ajv = require(require.resolve('ajv/dist/2020', { paths: [researchDir] }));
  assert.strictEqual(typeof Ajv, 'function', 'Ajv 2020 constructor is requireable');
  assert.ok(require.resolve('ajv-formats', { paths: [researchDir] }), 'ajv-formats resolves from the bundle directory');
});

test('7. no TypeScript toolchain was added to the app', () => {
  assert.strictEqual(pkg.devDependencies.typescript, undefined, 'no typescript dependency');
  assert.strictEqual(pkg.devDependencies.esbuild, undefined, 'no bundler added to the app build');
  assert.strictEqual(pkg.scripts.typecheck, undefined, 'no typecheck script');
  const tsFiles = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === 'node_modules' || entry.name === 'dist') continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.ts') || entry.name.endsWith('.tsx')) tsFiles.push(full);
    }
  };
  walk(root);
  assert.deepStrictEqual(tsFiles, [], 'no TypeScript sources inside the app');
  assert.ok(fs.existsSync(path.join(researchDir, 'prospect-research.ts')) === false, 'module source stayed in the module folder');
});

// --- A5 --------------------------------------------------------------------

test('8. the database is open before the research service is constructed', () => {
  const init = region(mainSource, 'function initServices()', 'function initResearch()');
  assert.ok(mainSource.includes('async function initServices()'), 'initServices is async');
  assert.ok(init.includes('await accountStore.ready;'), 'initServices awaits the real database');
  assert.ok(init.includes('new AccountStore()'), 'the existing AccountStore is still the data layer');
  const readyIdx = mainSource.indexOf('await accountStore.ready;');
  const researchIdx = mainSource.indexOf('function initResearch()');
  assert.ok(readyIdx > -1 && researchIdx > readyIdx, 'the await precedes research construction');
});

test('9. startup order is services, research, window, IPC, then a non-awaited start', () => {
  const startup = region(mainSource, 'app.whenReady()', "app.on('before-quit'");
  const marks = [
    'await initServices();',
    'initResearch();',
    'createMainWindow();',
    'registerIpcHandlers();',
    'applyProxyConfiguration(storedProxyUrl);',
    'startResearch();'
  ];
  let last = -1;
  for (const mark of marks) {
    const idx = startup.indexOf(mark);
    assert.ok(idx > -1, 'missing startup step: ' + mark);
    assert.ok(idx > last, 'startup step out of order: ' + mark);
    last = idx;
  }
});

test('10. gateway.start() is never awaited so the window cannot be delayed', () => {
  const startup = region(mainSource, 'app.whenReady()', "app.on('before-quit'");
  const startFn = region(mainSource, 'function startResearch()', '// A8: the base URL');
  assert.ok(!/await\s+[^;\n]*gateway\.start\(\)/.test(mainSource), 'no awaited start() anywhere in main');
  assert.ok(startup.includes('startResearch();'), 'start is delegated and not awaited by whenReady');
  assert.ok(startFn.includes('researchService.gateway.start()'), 'the gateway is started in startResearch()');
  assert.ok(startFn.includes('.catch('), 'start failure is caught, not unhandled');
  assert.ok(startFn.includes("logger.error('research', 'research start failed'"), 'start failure is logged');
  assert.ok(startFn.includes('researchService.quarantine.prune()'), 'quarantine is pruned after start');
  assert.ok(startFn.includes('if (!researchService) return;'), 'a null service is a no-op, not a crash');
});

test('11. initResearch builds objects only, and never takes the app down', () => {
  const init = region(mainSource, 'function loadResearchSettings', 'function startResearch');
  assert.ok(init.includes('try {') && init.includes('catch'), 'failures are contained');
  assert.ok(init.includes('researchService = null;'), 'an unusable service is cleared');
  assert.ok(init.includes("logger.error('research', 'research service unavailable'"), 'failure is logged');
  assert.ok(!init.includes('gateway.start'), 'no network call happens during construction');
  assert.ok(!init.includes('fetch('), 'construction performs no network I/O');
  assert.ok(!init.includes('dialog.'), 'no dialog during construction');
});

test('12. quit closes the research transport through a bounded, re-entrancy safe hook', () => {
  const quitHook = region(mainSource, "app.on('before-quit'", "app.on('window-all-closed'");
  assert.ok(quitHook.includes('event.preventDefault();'), 'the first quit is deferred');
  assert.ok(quitHook.includes('if (!researchService || researchClosing) return;'), 'guard prevents a re-entrant quit');
  assert.ok(quitHook.includes('service.close()'), 'the module close() is what runs');
  assert.ok(quitHook.includes('Promise.race(['), 'close is bounded by a race');
  assert.ok(quitHook.includes('setTimeout(resolve, 3000)'), 'the race has a 3s deadline');
  assert.ok(quitHook.includes('app.quit();'), 'the app quits once close settles');
  assert.ok(quitHook.includes("logger.error('research', 'close failed'"), 'a close failure is logged, not thrown');
  assert.ok(mainSource.includes("app.on('window-all-closed'"), 'existing quit behaviour preserved');
});

test('13. the composition root wires the real store, quarantine sink and credential source', () => {
  assert.ok(mainSource.includes("require('./src/main/prospect-research/research-service')"), 'required once from main');
  assert.strictEqual(mainSource.split("require('./src/main/prospect-research/research-service')").length - 1, 1, 'exactly one require');
  assert.ok(serviceSource.includes('new SqlResearchStateStore(opts.accountStore)'), 'store is built on the existing AccountStore');
  assert.ok(serviceSource.includes('new SqlQuarantineSink(opts.accountStore'), 'quarantine is built on the existing AccountStore');
  assert.ok(serviceSource.includes('new ZuniSeoCredentialSource({ secretsDir: opts.secretsDir })'), 'credential source is constructed');
  assert.ok(serviceSource.includes('quarantine,'), 'the real sink is passed to the module');
  assert.ok(serviceSource.includes('credentials: keys,'), 'the real credential source is passed to the module');
  assert.ok(!serviceSource.includes('TODO(A2)') && !serviceSource.includes('TODO(A3)'), 'no A2/A3 placeholders remain');
  assert.ok(!serviceSource.includes('deferredQuarantineSink'), 'the placeholder sink is gone');
});

test('14. A1 store contract holds in code, not just in tests', () => {
  assert.ok(storeSource.includes("require('./prospect-research.cjs')"), 'the store takes the error class from the bundle');
  assert.ok(storeSource.includes('WHERE id = ? AND version = ?'), 'CAS is done in SQL');
  assert.ok(storeSource.includes('this.#db().getRowsModified() !== 1'), 'the row count decides the outcome');
  assert.ok(storeSource.includes('throw new StaleRecordError(record.id)'), 'the bundle class is thrown, not a look-alike');
  assert.ok(!storeSource.includes("err.name === 'StaleRecordError'"), 'no name matching');
  assert.ok(!storeSource.includes('class StaleRecordError'), 'no locally redefined error class');
  const insertBody = region(storeSource, 'async insert(record)', 'async update(record)');
  assert.ok(insertBody.includes('this.accountStore.saveDB();'), 'insert flushes inside the call');
  const updateBody = region(storeSource, 'async update(record)', 'async get(id)');
  assert.ok(updateBody.includes('this.accountStore.saveDB();'), 'update flushes inside the call');
  const updateIdx = updateBody.indexOf('getRowsModified() !== 1');
  const flushIdx = updateBody.indexOf('this.accountStore.saveDB();');
  assert.ok(updateIdx > -1 && flushIdx > updateIdx, 'the flush only happens after the CAS succeeded');
});

test('15. A6 stays deferred: the Lead Agent entry point is unreachable', () => {
  assert.ok(!mainSource.includes('evidenceForLeadAgent'), 'main never calls it');
  assert.ok(!storeSource.includes('evidenceForLeadAgent'), 'no adapter calls it');
  assert.ok(!serviceSource.replace(/\/\/.*$/gm, '').includes('evidenceForLeadAgent'), 'no live code path calls it');
  assert.ok(!preloadSource.includes('evidenceForLeadAgent'), 'the renderer cannot reach it');
  assert.ok(!ipcSource.includes('evidenceForLeadAgent'), 'no IPC channel exposes it');
  assert.ok(serviceSource.includes('A6 (deferred until a Lead Agent exists)'), 'the deferral is documented in the composition root');
  // F7 declared lock update: 7 -> 8, the read-only prospect-research:list overview channel (still no agent channel).
  assert.strictEqual(researchChannels().length, 8, 'exactly the eight approved channels exist - no agent channel');
});

// --- A4 -------------------------------------------------------------------

test('16. the seven research channels are registered by ZTech, not the bundle', () => {
  const bundle = require(bundlePath);
  assert.strictEqual(bundle.registerProspectResearchIpc, undefined, 'the bundle does not export registerProspectResearchIpc');
  assert.strictEqual(bundle.SafeStorageCredentialStore, undefined, 'the bundle does not export SafeStorageCredentialStore');
  assert.ok(fs.existsSync(path.join(researchDir, 'research-ipc.js')), 'ZTech registers the channels itself');
  const names = researchChannels().sort();
  assert.deepStrictEqual(names, [
    'prospect-research:clear-api-key',
    'prospect-research:get',
    'prospect-research:import-artifact',
    'prospect-research:key-status',
    // F7 declared lock update: the read-only Research workspace overview.
    'prospect-research:list',
    'prospect-research:provider-health',
    'prospect-research:request',
    'prospect-research:set-api-key'
  ], 'the eight approved channel names are registered');
  for (const ch of names) {
    assert.ok(preloadSource.includes(`'${ch}'`), 'exposed through the preload allow-list: ' + ch);
  }
});

test('17. every research channel is sender-checked and takes no renderer path', () => {
  const handlers = (ipcSource.match(/ipcMain\.handle\(/g) || []).length;
  const guards = (ipcSource.match(/guard\(async/g) || []).length;
  // F7 declared lock update: 7 -> 8 handlers, every one still sender-guarded.
  assert.strictEqual(handlers, 8, 'eight handlers');
  assert.strictEqual(guards, 8, 'every handler is wrapped in the sender guard');
  assert.ok(ipcSource.includes("throw new Error('Untrusted sender.')"), 'an untrusted sender is refused');
  assert.ok(ipcSource.includes('opts') || ipcSource.includes('d.isTrustedSender(event) === true'), 'the guard consults the injected check');
  // The import channel must never read a path from the renderer.
  const importBody = region(ipcSource, 'CHANNELS.importArtifact, guard', 'CHANNELS.providerHealth');
  assert.ok(importBody.includes('await d.showOpenDialog()'), 'main owns the file dialog');
  assert.ok(!importBody.includes('args[1]') && !importBody.includes('filePath:'), 'no path is taken from the renderer payload');
  assert.ok(mainSource.includes('dialog.showOpenDialog('), 'the dialog is opened in main');
  assert.ok(mainSource.includes("extensions: ['json']"), 'the dialog is filtered to json');
  assert.ok(mainSource.includes('properties: [\'openFile\']'), 'the dialog selects a single file');
  assert.ok(!preloadSource.includes("importArtifact: (leadRef, path)"), 'preload passes no path');
  assert.ok(preloadSource.includes("importArtifact: (leadRef) =>"), 'preload forwards only the lead id');
});

test('18. website and name come from the database, market and language stay null', () => {
  const loadLead = region(mainSource, 'async function loadResearchLead', '// A4/A7: the renderer never names a file');
  assert.ok(loadLead.includes('accountStore.queryNumbers({ limit: 1, offset: 0, id: leadRef })'), 'the lead is read by id from the existing store');
  assert.ok(loadLead.includes('website: asText(lead.website)'), 'website comes from the lead row');
  assert.ok(loadLead.includes('companyName: asText(lead.title)'), 'company name maps to the existing title column');
  assert.ok(loadLead.includes('market: null'), 'market stays null');
  assert.ok(loadLead.includes('language: null'), 'language stays null');
  assert.ok(!storeSource.includes('country') && !storeSource.includes('market'), 'no lead columns were added');
  const requestHandler = region(ipcSource, 'CHANNELS.request, guard', 'CHANNELS.get, guard');
  assert.ok(requestHandler.includes('await d.loadLead(leadRefOf(leadRef))'), 'the request handler loads the lead in main');
  assert.ok(requestHandler.includes("throw new Error('Lead not found.')"), 'a missing lead is refused');
  assert.ok(!requestHandler.includes('args[1].website'), 'no website is taken from the renderer payload');
});

test('19. the Zuni-SEO key is write-only across every boundary', () => {
  const setKey = region(ipcSource, 'CHANNELS.setApiKey, guard', 'CHANNELS.clearApiKey');
  assert.ok(setKey.includes("return { configured: true, provider:"), 'set-api-key returns a boolean and the provider state only');
  assert.ok(!setKey.includes('key:'), 'the key is never echoed back');
  const keyStatus = region(ipcSource, 'CHANNELS.keyStatus', 'return { channels:');
  assert.ok(keyStatus.includes('configured: await d.keys.hasApiKey()'), 'key-status returns a boolean only');
  assert.ok(!ipcSource.includes('getApiKey()'), 'no channel calls getApiKey()');
  const clearKey = region(ipcSource, 'CHANNELS.clearApiKey', 'CHANNELS.keyStatus');
  assert.ok(clearKey.includes('return { configured: false };'), 'clear-api-key returns a boolean only');
  assert.ok(credentialSource.includes('never logged'), 'the credential source documents the no-logging rule');
  const credentialCode = credentialSource.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  assert.ok(!/(logger|console)\s*\./.test(credentialCode), 'the credential source logs nothing');
  // Renderer: writes once, never reads back, never holds the value.
  const applyForm = region(rendererSource, 'function applyResearchSettingsToForm', 'async function refreshResearchHealth');
  assert.ok(applyForm.includes("if (key) key.value = '';"), 'the key field is always emptied on load');
  assert.ok(!applyForm.includes('researchKeyValue'), 'the key is not stored in renderer state');
  assert.ok(rendererSource.includes('saveResearchKey'), 'the renderer writes the key once');
  const writeKey = region(rendererSource, 'async function saveResearchKey', 'async function clearResearchKey');
  assert.ok(writeKey.includes('input.value = \'\';'), 'the key field is scrubbed after writing');
  assert.ok(!writeKey.includes('settings.load'), 'the key is never fetched back from settings');
});

// --- A2 / A3 / A8 ---------------------------------------------------------

test('20. A2 quarantine stores truncated payloads and prunes to the same retention', () => {
  assert.ok(quarantineSource.includes('async put(item)'), 'the port method is put(), not quarantine()');
  assert.ok(quarantineSource.includes("const TABLE = 'prospect_research_quarantine'"), 'it has its own table');
  assert.ok(quarantineSource.includes('CREATE TABLE IF NOT EXISTS ${TABLE}'), 'created in the existing database');
  assert.ok(!quarantineSource.includes('initSqlJs'), 'no second database engine is introduced');
  assert.ok(quarantineSource.includes('truncateUtf8(serialized, this.maxPayloadBytes)'), 'oversized payloads are truncated');
  assert.ok(quarantineSource.includes('kept.truncated ? 1 : 0'), 'the truncated flag is persisted');
  assert.ok(quarantineSource.includes('async prune()'), 'retention pruning exists');
  assert.ok(quarantineSource.includes('WHERE received_at < ?'), 'pruning is by age');
  const putBody = region(quarantineSource, 'async put(item)', 'async list(');
  assert.ok(putBody.includes('this.accountStore.saveDB();'), 'a quarantined payload is flushed inside the call');
  assert.ok(serviceSource.includes('retentionMs: RESEARCH_DEFAULTS.freshness.staleAfterHours'), 'retention matches the freshness policy');
  assert.ok(mainSource.includes('researchService.quarantine.prune()'), 'pruning runs at startup');
});

test('21. A3 reuses the existing vault and confines basic_text refusal to the Zuni-SEO key', () => {
  assert.ok(credentialSource.includes("require('../credentialVault')"), 'the existing vault is reused');
  assert.ok(credentialSource.includes('credentialVault.seal(trimmed)'), 'the existing sealed format is used');
  assert.ok(credentialSource.includes('credentialVault.reveal(stored)'), 'stored keys are revealed through the vault');
  assert.ok(credentialSource.includes('assertSecureBackend()'), 'the Zuni-SEO key has its own backend guard');
  const guard = region(credentialSource, 'function assertSecureBackend()', 'function isPlainObject');
  assert.ok(guard.includes("backend === 'basic_text'"), 'basic_text is refused');
  assert.ok(guard.includes('isEncryptionAvailable'), 'unavailable encryption is refused');
  // credentialVault.js must be untouched by this decision.
  const vaultSource = fs.readFileSync(path.join(root, 'src', 'main', 'credentialVault.js'), 'utf8');
  assert.ok(!vaultSource.includes('basic_text'), 'the vault itself does not learn about basic_text');
  assert.ok(!vaultSource.includes('zuni'), 'the vault does not know about the Zuni-SEO key');
  assert.ok(vaultSource.includes("const CREDENTIAL_FIELDS = ['apiKey', 'taskKey'];"), 'vault credential fields unchanged');
  assert.ok(vaultSource.includes('setSafeStorageForTests'), 'the vault test seam is preserved');
  const setKey = region(credentialSource, 'async setApiKey(key)', '/** ZuniSeoKeyWriter. */');
  assert.ok(setKey.includes('KEY_FORMAT.test(trimmed)'), 'the zsk_ key format is validated');
  assert.ok(setKey.includes('assertSecureBackend();'), 'the backend is checked before sealing');
  assert.ok(setKey.includes('mode: KEY_FILE_MODE'), 'the key file is written 0600');
  assert.ok(setKey.includes('renameSync(tmpPath, this.filePath)'), 'the key file is written atomically');
});

test('22. A8 exposes only the base URL and transport, and recreates on change', () => {
  const validate = region(mainSource, 'function validateSettingsPayload', 'function validateSubmitShape');
  assert.ok(validate.includes('assertPlainObject(settings.research'), 'research settings are shape-checked');
  assert.ok(validate.includes('prospectResearch.validateBaseUrl('), 'the base URL is validated on save');
  assert.ok(validate.includes('prospectResearch.validateTransport('), 'the transport is validated on save');
  assert.ok(!validate.includes('timeoutMs') && !validate.includes('retry') && !validate.includes('breaker') && !validate.includes('freshness'),
    'timeouts, retry, breaker and freshness are not user-editable');
  // Validation rules.
  const urlRules = region(serviceSource, 'function validateBaseUrl', 'function validateTransport');
  assert.ok(urlRules.includes("url.protocol === 'https:'"), 'https is accepted');
  assert.ok(urlRules.includes('LOOPBACK_HOSTS.includes(url.hostname)'), 'plain http is accepted only for loopback');
  assert.ok(urlRules.includes('must use HTTPS'), 'plain http elsewhere is refused');
  assert.ok(urlRules.includes('must not contain credentials'), 'credentials in the URL are refused');
  // Recreate, never silently continue.
  const recreate = region(mainSource, 'async function recreateResearchService', '// A4: the lead\'s website');
  assert.ok(recreate.includes('await Promise.race(['), 'the old service close is bounded');
  assert.ok(recreate.includes('previous.close()'), 'the old service is actually closed');
  assert.ok(recreate.includes('initResearch();'), 'a new service is constructed');
  assert.ok(recreate.includes('startResearch();'), 'the new service is started');
  const saveRegion = region(mainSource, "ipcMain.handle('settings:save'", "ipcMain.handle('settings:load'");
  assert.ok(saveRegion.includes('researchSettingsChanged(researchService'), 'a change is detected before recreating');
  assert.ok(saveRegion.includes('await recreateResearchService();'), 'the change triggers a recreate');
  assert.ok(saveRegion.includes('return { success: true, proxyApplied: proxyResult.applied };'), 'the success envelope is unchanged');
  assert.ok(saveRegion.includes("settingsRecord.research = nextSettings.research"), 'the research settings are persisted');
  // Defaults stay in code.
  const defaults = region(serviceSource, 'const RESEARCH_DEFAULTS', 'const ALLOWED_TRANSPORTS');
  for (const key of ['timeoutMs', 'preflightTimeoutMs', 'retry', 'breaker', 'freshness', 'schedulerTickMs', 'artifactMaxBytes']) {
    assert.ok(defaults.includes(key), 'code default retained: ' + key);
  }
  assert.ok(rendererSource.includes("id=\"settings-research-transport\"") || htmlSource.includes('id="settings-research-transport"'),
    'only base URL and transport are exposed in the form');
  assert.ok(!htmlSource.includes('settings-research-timeout'), 'no timeout field in the UI');
});

test('23. A7 renders the nine distinct availability states as untrusted text', () => {
  for (const id of ['lead-detail-research', 'lead-detail-research-body', 'btn-research-refresh', 'btn-research-import']) {
    assert.ok(htmlSource.includes(`id="${id}"`), 'markup present: ' + id);
  }
  for (const state of ['no_website', 'not_checked', 'pending', 'site_unreachable',
    'no_crawlable_content', 'partial', 'complete', 'failed', 'stale']) {
    assert.ok(rendererSource.includes(`${state}:`), 'availability state handled: ' + state);
  }
  const template = region(rendererSource, 'function leadResearchTemplate', 'function renderLeadResearch');
  assert.ok(template.includes('escapeHtml('), 'every rendered value is escaped');
  assert.ok(!template.includes('innerHTML ='), 'the template returns a string, it does not assign');
  const untrusted = region(rendererSource, 'function researchUntrustedText', 'function leadResearchTemplate');
  assert.ok(untrusted.includes('escapeHtml('), 'quoted site text is escaped');
  assert.ok(untrusted.includes('UNTRUSTED'), 'quoted text is delimited as untrusted');
  assert.ok(untrusted.includes('not instructions'), 'the untrusted nature is stated in the UI');
  assert.ok(rendererSource.includes("window.appAPI.research.request(leadId, true)"), 'Refresh forces a new run');
  assert.ok(rendererSource.includes('window.appAPI.research.importArtifact(leadId)'), 'Import passes only the lead id');
  assert.ok(rendererSource.includes('closeLeadDetail') && rendererSource.includes("researchRegion.hidden = true"),
    'the research panel is hidden when the Lead Profile closes');
});

for (const [name, fn] of tests) {
  try {
    fn();
    passed++;
    console.log('ok - ' + name);
  } catch (err) {
    failed++;
    console.log('FAIL - ' + name);
    console.log(String((err && err.stack) || err));
  }
}

console.log(`${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
