<#
.SYNOPSIS
    Refreshes the prebuilt Zuni-SEO prospect-research CommonJS bundle inside ZTech.

.DESCRIPTION
    The module's TypeScript source and its tests stay in the module folder. Only
    dist\prospect-research.cjs is copied into the app, because ZTech's main process
    is CommonJS and has no TypeScript toolchain.

    Steps: install the module's dependencies, run its CJS build, copy the artefact,
    then verify the copied file really is the pinned version and that it loads.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\sync-prospect-research.ps1
    powershell -ExecutionPolicy Bypass -File scripts\sync-prospect-research.ps1 -ModuleRoot G:\ztech-integration\ztech-prospect-research
#>
[CmdletBinding()]
param(
    [string]$ModuleRoot = 'G:\ztech-integration\ztech-prospect-research',
    [string]$ExpectedVersion = '0.1.2'
)

$ErrorActionPreference = 'Stop'

function Fail([string]$message) {
    Write-Error $message
    exit 1
}

$appRoot      = Split-Path -Parent $PSScriptRoot
$targetDir    = Join-Path $appRoot 'src\main\prospect-research'
$targetFile   = Join-Path $targetDir 'prospect-research.cjs'
$modulePkg    = Join-Path $ModuleRoot 'package.json'
$moduleBundle = Join-Path $ModuleRoot 'dist\prospect-research.cjs'

Write-Host "module : $ModuleRoot"
Write-Host "target : $targetFile"

if (-not (Test-Path -LiteralPath $modulePkg))    { Fail "module package.json not found: $modulePkg" }
if (-not (Test-Path -LiteralPath $moduleRoot))  { Fail "module folder not found: $ModuleRoot" }

# 1. the module's own version must match the pin
$moduleVersion = (Get-Content -LiteralPath $modulePkg -Raw | ConvertFrom-Json).version
if ($moduleVersion -ne $ExpectedVersion) {
    Fail "module is v$moduleVersion but this app is pinned to v$ExpectedVersion. Update the pin deliberately, do not sync silently."
}

# 2. install + build in the module folder
Push-Location $ModuleRoot
try {
    Write-Host "`n[1/4] npm install (module dependencies)"
    & npm install
    if ($LASTEXITCODE -ne 0) { Fail "npm install failed in $ModuleRoot" }

    Write-Host "`n[2/4] npm run build:cjs"
    & npm run build:cjs
    if ($LASTEXITCODE -ne 0) { Fail "npm run build:cjs failed in $ModuleRoot" }
}
finally {
    Pop-Location
}

if (-not (Test-Path -LiteralPath $moduleBundle)) { Fail "build produced no artefact: $moduleBundle" }

# 3. copy into the app
if (-not (Test-Path -LiteralPath $targetDir)) {
    New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
}
Write-Host "`n[3/4] copying bundle into the app"
Copy-Item -LiteralPath $moduleBundle -Destination $targetFile -Force

# 4. verify what actually landed in the app
Write-Host "`n[4/4] verifying"
$header = (Get-Content -LiteralPath $targetFile -TotalCount 1).Trim()
if ($header -ne "/* ztech-prospect-research $ExpectedVersion - generated by npm run build:cjs, do not edit */") {
    Fail "copied bundle header is unexpected: $header"
}
Write-Host "  header  : $header"

$sourceHash = (Get-FileHash -LiteralPath $moduleBundle -Algorithm SHA256).Hash
$targetHash = (Get-FileHash -LiteralPath $targetFile   -Algorithm SHA256).Hash
if ($sourceHash -ne $targetHash) { Fail "copy verification failed: SHA256 mismatch" }
Write-Host "  sha256  : $targetHash"

# The bundle must load as CommonJS and expose the classes the adapters import.
Push-Location $appRoot
try {
    $env:PR_BUNDLE = $targetFile
    $env:PR_ROOT   = $appRoot
    $probe = @'
const path = require('path');
const bundle = require(process.env.PR_BUNDLE);
for (const name of ['createProspectResearch', 'StaleRecordError']) {
  if (typeof bundle[name] !== 'function') { throw new Error('missing export: ' + name); }
}
const e = new bundle.StaleRecordError('probe');
if (e.name !== 'StaleRecordError') { throw new Error('StaleRecordError identity lost'); }
// Resolve exactly the way the bundle will, from the bundle's own folder.
const from = path.dirname(process.env.PR_BUNDLE);
const ajvPkg = require(require.resolve('ajv/package.json', { paths: [from] }));
const formatsPkg = require(require.resolve('ajv-formats/package.json', { paths: [from] }));
require(require.resolve('ajv/dist/2020', { paths: [from] }));
console.log('  exports : ' + Object.keys(bundle).sort().join(', '));
console.log('  deps    : ajv ' + ajvPkg.version + ', ajv-formats ' + formatsPkg.version + ', ajv/dist/2020 ok');
'@
    $probeFile = Join-Path $env:TEMP ('ztech-pr-probe-' + [guid]::NewGuid().ToString('N') + '.js')
    Set-Content -LiteralPath $probeFile -Value $probe -Encoding UTF8
    try {
        $probeOutput = & node $probeFile 2>&1
        if ($LASTEXITCODE -ne 0) { Fail "bundle does not load: $probeOutput" }
        $probeOutput | ForEach-Object { Write-Host "$_" }
    }
    finally {
        Remove-Item -LiteralPath $probeFile -Force -ErrorAction SilentlyContinue
        Remove-Item Env:\PR_BUNDLE -ErrorAction SilentlyContinue
        Remove-Item Env:\PR_ROOT   -ErrorAction SilentlyContinue
    }
}
finally {
    Pop-Location
}

Write-Host "`nsynced ztech-prospect-research v$ExpectedVersion"
exit 0
